---
title: "Final Report"
author: "Group 1: Jiawen Chen, Brooke Felsheim, Elena Kharitonova, Jairui Tang, and Xinjie Qian"
date: "4/29/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

```{r}
library(usethis)
library(devtools)
load_all("package/bikeSharing")
set.seed(1)
```

```{r}
str(london)
str(dc)
str(seoul)
```

```{r}
london_train <- london[london$Year == "Year 1",]
london_test <- london[london$Year == "Year 2",]
```


# Methods

## Negative Binomial Generalized Linear Mixed Model

## Random Forest

# Results 

## Negative Binomial Generalized Linear Mixed Model
```{r eval=FALSE, include=TRUE}
glmm_fit <- MCEM_algorithm( beta_initial = c(8.3, 1.5, 1.5, -0.25, -0.50, 0, 
                                             0, -0.25, 0, 0, 0, 0, 0, -0.25),
                         theta_initial = 10,
                         s2gamma_initial = 0.2,
                         M = 1000,
                         burn.in = 200,
                         tol = 10^-4,
                         maxit = 100,
                         data = london_train
                         )
```
```{r}
str(glmm_fit)
```
```{r}
glmm_model_fit(glmm_fit, london_train, scale_to_london_mean = "no") 
glmm_model_fit(glmm_fit, london_test, scale_to_london_mean = "no") 
glmm_model_fit(glmm_fit, dc, scale_to_london_mean = "yes") 
glmm_model_fit(glmm_fit, seoul, scale_to_london_mean = "yes") 
```


## Random Forest
```{r}
rf_fit <- train_random_forest(data = london_train)
rf_fit
plot_rf_importance(london_train)
```

```{r}
rf_model_fit(rf_fit, london_train, scale_to_london_mean = "no")
rf_model_fit(rf_fit, london_test, scale_to_london_mean = "no") 
rf_model_fit(rf_fit, dc, scale_to_london_mean = "yes") 
rf_model_fit(rf_fit, seoul, scale_to_london_mean = "yes") 
```



```{r}
seoul$city = "Seoul - Scaled"
london_train$city = "London"
london_test$city = "London"
dc$city = "DC - Scaled"
seoul$city2 = "Seoul - Scaled"
london_train$city2 = "London - Train"
london_test$city2 = "London - Test"
dc$city2 = "DC - Scaled"
scale_seoul = mean(seoul$Bike_count)/
  mean(london$Bike_count)
scale_dc = mean(dc$Bike_count)/
  mean(london$Bike_count)
seoul$Bike_count2 = seoul$Bike_count / scale_seoul
london_test$Bike_count2 = london_test$Bike_count 
london_train$Bike_count2 = london_train$Bike_count 
dc$Bike_count2 = dc$Bike_count / scale_dc
seoul$Year = 1


all_data =rbind(seoul, london_train, london_test, dc)
all_data$city = factor(all_data$city, levels = c("London",  "DC - Scaled", "Seoul - Scaled"))
all_data$city2 = factor(all_data$city2, levels = c("London - Train", "London - Test", "DC - Scaled", "Seoul - Scaled"))


ggplot(all_data, aes(x = Bike_count2))+geom_histogram(fill = "dark blue",aes(y = stat(density)), bins = 30)+facet_wrap(~city2)+
  theme_classic()+xlim(0,30000) + labs(title = "Distribution of Bike Counts for Cities", y = "Density", x = "Bike Count")

mean(london_test$Bike_count)
mean(london_train$Bike_count)

```


# Discussion
